// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp05YowCE1hs0rHuLyQJmukbIb6IRiXI4',
    appId: '1:842965336708:web:5b9a6a5a536bda2a8078d1',
    messagingSenderId: '842965336708',
    projectId: 'chat-4f46f',
    authDomain: 'chat-4f46f.firebaseapp.com',
    storageBucket: 'chat-4f46f.appspot.com',
    measurementId: 'G-RCD82C4JDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrM1v4t8XAk9c899doypDHYq0bryY719E',
    appId: '1:842965336708:android:fce97541b2801b368078d1',
    messagingSenderId: '842965336708',
    projectId: 'chat-4f46f',
    storageBucket: 'chat-4f46f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhJDW9yVTEtT9hVwuw7Gh5ifM5-3GhGU',
    appId: '1:842965336708:ios:4dc5c40272f23eb48078d1',
    messagingSenderId: '842965336708',
    projectId: 'chat-4f46f',
    storageBucket: 'chat-4f46f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhJDW9yVTEtT9hVwuw7Gh5ifM5-3GhGU',
    appId: '1:842965336708:ios:fc859f7267a097418078d1',
    messagingSenderId: '842965336708',
    projectId: 'chat-4f46f',
    storageBucket: 'chat-4f46f.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
